# Generated by Django 4.2.11 on 2024-04-16 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content2',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
