# Generated by Django 4.2.11 on 2024-04-18 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0004_remove_review_content2'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
