# Generated by Django 4.2.11 on 2024-04-09 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_created_at_movie_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='is_open',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
